draw_self()
draw_set_valign(fa_middle)
draw_set_halign(fa_center)
draw_set_font(font_nes)
draw_text_transformed(x,y,"Click to Play",0.5,0.5,image_angle)
draw_text_transformed(x,y-100,"",1,1,image_angle)